/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// autoSidebar: [{ type: "autogenerated", dirName: "." }],
	// But you can create a sidebar manually
	modulSidebar: [
		// {
		// 	type: "doc",
		// 	id: "start",
		// 	label: "Getting Started",
		// },
		{
			type: "category",
			label: "Getting Started",
			link: {
				type: "generated-index",
			},
			items: [
				"getting-started/aturan-praktikum",
				"getting-started/start",
				"getting-started/animate",
				"getting-started/ilustrator",
				"getting-started/unity",
			],
		},
		{
			type: "doc",
			id: "modul-anigame/bab1",
		},
		{
			type: "doc",
			id: "modul-anigame/bab2",
		},
		{
			type: "doc",
			id: "modul-anigame/bab3",
		},
		{
			type: "doc",
			id: "modul-anigame/bab4",
		},
		{
			type: "doc",
			id: "modul-anigame/bab5",
		},
		{
			type: "doc",
			id: "modul-anigame/bab6",
		},
		{
			type: "doc",
			id: "modul-anigame/bab7",
		},
		{
			type: "doc",
			id: "modul-anigame/bab8",
		},
		{
			type: "doc",
			id: "modul-anigame/bab9",
		},
		{
			type: "doc",
			id: "modul-anigame/bab10",
		},
	],
};

export default sidebars;
