/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// autoSidebar: [{ type: "autogenerated", dirName: "." }],
	// But you can create a sidebar manually
	modulSidebar: [
		// Getting Started
		{
			type: "category",
			label: "GETTING STARTED",
			link: {
				type: "generated-index",
			},
			items: [
				"getting-started/aturan-praktikum",
				// "getting-started/perihal-tugas",
				"getting-started/start",
			],
		},

		// Bab 1
		{
			type: "category",
			label: "BAB 1",
			link: {
				type: "generated-index",
			},
			items: ["modul-anigame/bab1/modul", "modul-anigame/bab1/tugas"],
		},

		// Bab 2
		{
			type: "category",
			label: "BAB 2",
			link: {
				type: "generated-index",
			},
			items: [
				"modul-anigame/bab2/modul",
				"modul-anigame/bab2/bahan",
				"modul-anigame/bab2/tugas",
			],
		},

		// Bab 3
		{
			type: "category",
			label: "BAB 3",
			link: {
				type: "generated-index",
			},
			items: [
				"modul-anigame/bab3/modul",
				"modul-anigame/bab3/bahan",
				"modul-anigame/bab3/tugas",
			],
		},
	],
};

export default sidebars;
